### ISSUE TITLE
TypeError: Cannot read property 'categories' of undefined

### ISSUE THREAD

**Issue by yamadapc** [adcpm/busy#123]
This error needs to be treated:

https://github.com/adcpm/busy/blob/dev/src/app/Sidebar.js#L71-L80

- - -

https://sentry.io/beijaflor/busy-application/issues/179202121/

```
TypeError: Cannot read property 'categories' of undefined
  at None (./src/app/Sidebar.js:27:15)
...
(2 additional frame(s) were not displayed)
```

**Comment by adcpm** [comment]
Fixed
