### ISSUE TITLE
Cant submit comment on mobile

### ISSUE THREAD

**Issue by adcpm** [adcpm/busy#128]
Actually i cant submit a comment on mobile. There is no button and also dont have a submit button on mobile keyboard to submit a reply.

**Comment by p0o** [comment]
I tried it actually works the same way we do on desktop by pressing enter but for the nature of android you should press enter 2 times (the first time it accepts auto-correct suggestion)

I believe it should be tracked at #136

**Comment by adcpm** [comment]
This issue has been fixed
