### ISSUE TITLE
Access to another user profil page from a profil page will not update the header info

### ISSUE THREAD

**Issue by mynameisek** [adcpm/busy#152]
![profilebug2](https://cloud.githubusercontent.com/assets/8390894/20652721/da3b67b4-b4fe-11e6-8310-42443ad09f48.gif)

from https://dev.busy.org/@ekitcho
if you click on @steemfest url it should also update the header profile. For now it does not update and keep the first profile info you visited

**Comment by mynameisek** [comment]
User updating now, but : 
secondary-nav does not (Posts/VotingPower/Followers bar)
@p0o

**Comment by p0o** [comment]
@mynameisek may you check #154 again
