### ISSUE TITLE
add json_meta app-identifier busy

### ISSUE THREAD

**Issue by roelandp** [adcpm/busy#190]
Hi, I noticed @feruzm uses for eSteem the following json_meta for posting from his app: 

`app: 'esteem/'+$appversion`

This could be a defacto standard for identifying posts coming from different apps onto the blockchain. Might be cool to add it to posts created from busy: 

`app: busy/0.0.1`

**Comment by adcpm** [comment]
Indeed, Steemit is using it too and we are now using it too since recent changes on development repo see a post example: https://steemd.com/test/@siol/test

**Comment by roelandp** [comment]
great. can be closed then :)
