### ISSUE TITLE
Padding margin on table markdown

### ISSUE THREAD

**Issue by mynameisek** [adcpm/busy#201]
add some padding/margin on table markdown style
![image](https://cloud.githubusercontent.com/assets/8390894/21430292/d53efd26-c862-11e6-8902-a877a02c4819.png)

![image](https://cloud.githubusercontent.com/assets/8390894/21430296/dc57d8bc-c862-11e6-9e34-0f10e19bcde8.png)

**Comment by adcpm** [comment]
This is about css it's for me

**Comment by mynameisek** [comment]
more issue 👍 
![image](https://cloud.githubusercontent.com/assets/8390894/21471390/ea208f24-cab1-11e6-80fe-ded5bbc205c0.png)
real look

![image](https://cloud.githubusercontent.com/assets/8390894/21471393/f45600e6-cab1-11e6-8f24-ddb5977c51d6.png)
