### ISSUE TITLE
Android default browser show blank screen

### ISSUE THREAD

**Issue by adcpm** [adcpm/busy#217]
Just tested on Samsung S6 / S7 and Alpha, with default browser opening app.busy.org it will give a blank screen.

**Comment by nil1511** [comment]
Can you check this again? Working for me now.

**Comment by adcpm** [comment]
I still see a blank screen. 
![image](https://cloud.githubusercontent.com/assets/16245250/22183503/7fdee136-e0f2-11e6-99f0-b8e8ce88f68e.png)

Are you sure that you are using this app:
![image](https://cloud.githubusercontent.com/assets/16245250/22183514/b4b74e70-e0f2-11e6-99da-e899eb9d5fd7.png)

**Comment by nil1511** [comment]
I tested on chrome for mobile.

**Comment by adcpm** [comment]
It's not Chrome.
