### ISSUE TITLE
Post article with json_metadata details

### ISSUE THREAD

**Issue by adcpm** [adcpm/busy#220]
We previously had json_metadata details when posting new article see: https://steemd.com/tx/61933dcf1fadfbf074c2b2049fb781315fa67f81
![image](https://cloud.githubusercontent.com/assets/16245250/21708262/4fa430b6-d409-11e6-8e4c-5648fa939b18.png)
We need it back

**Comment by nil1511** [comment]
json_metadata are there on new post. check https://steemd.com/spam/@test1234/159722ac1ac-new-test

**Comment by adcpm** [comment]
Just tried and i dont see it https://steemd.com/test/@siol/1b5p3a99l-hey-yo

**Comment by nil1511** [comment]
It is working on dev.busy https://steemd.com/tx/f03da7d549024281878385f0f3fa297b26e2ee3f 
May be your node_modules are outdated. update those for steemconnect.com and busy.

**Comment by adcpm** [comment]
You right, my bad
