### ISSUE TITLE
Votes are not sent to the blockchain 

### ISSUE THREAD

**Issue by tibonova** [adcpm/busy#233]
Voting doesn't work. First I've asked in steemit.chat, and since the answer was it should work, I'm opening this issue.

When I vote for a post and check it after on Steemit, it shows I didn't vote. I've checked also at steemd.com and steemdb.com.

An example:

**On Busy**
[![busy-bug9c04e.md.png](http://www.steemimg.com/images/2017/01/10/busy-bug9c04e.md.png)](http://www.steemimg.com/image/oqP5w)

**On Steemit**
[![busy-steemit87494.md.png](http://www.steemimg.com/images/2017/01/10/busy-steemit87494.md.png)](http://www.steemimg.com/image/oqd3W)

Links: [Steemd](https://steemd.com/witness-category/@timcliff/reports-from-the-witnesses-2017-01-08), [Steemdb](https://steemdb.com/witness-category/@timcliff/reports-from-the-witnesses-2017-01-08)

*Note:* steemd.com is down for me now but I've tested another vote on it earlier with the same result.

**Comment by p0o** [comment]
@tibonova Thank you very much for submitting this issue. I just tried to replicate the issue but I can see both of my votes that I clicked on Steemit as well. However to understand the real cause I need more information from you:

1. Do you have any error on your [Chrome Console](https://developers.google.com/web/tools/chrome-devtools/console/)?
2. Can you use any other broadcast functionality of busy correctly? Like sending a comment or voting a comment?
3. Do you have another account to test? Would appreciate it.

**Comment by tibonova** [comment]
I couldn't comment (it didn't show up even on Busy).
I used Firefox, so I wanted to try it in Chromium as well, but I couldn't login at SteemConnect. I logout *after this* in FF, and tried it again in Chromium with no luck.
Now, I cannot login neither in Cromium, nor in Firefox.

SteemConnect gives an error message.

**Firefox**
`JSON.parse: unexpected character at line 1 column 1 of the JSON data`

**Chromium**
`Unexpected token < in JSON at position 0`
*Console*
`https://steemconnect.com/auth/login Failed to load resource: the server responded with a status of 503 ()`

**Comment by tibonova** [comment]
I had time to try it again today. 

I tested voting and commenting, and it's working now as expected, I've checked on Steemd. 

I don't know what you've fixed meanwhile (for I don't do anything differently). I spot some updates, though. ;)
