### ISSUE TITLE
Youtube Embed video url inpost (Playlist)

### ISSUE THREAD

**Issue by mynameisek** [adcpm/busy#260]
![image](https://cloud.githubusercontent.com/assets/8390894/22113995/519a7d08-de68-11e6-84b6-4a38cad95dc4.png)
" https://www.youtube.com/watch?v=KoQ-ygFgnk8&index=3&list=PL30E9A58C854F5A52  " wont transform in embed video playlist (might be because of the list= for playlist)

**Comment by adcpm** [comment]
This issue has been fixed.
