### ISSUE TITLE
The elapsed time meter shows wrong data

### ISSUE THREAD

**Issue by tibonova** [adcpm/busy#262]
I've made a [post](https://steemit.com/stemms/@tibonova/pierce-the-butter-1485035761-9213154). Checked it on my Busy [profile page](https://app.busy.org/@tibonova), and it showed I've submitted it an hour ago. That was not true (maybe half an hour old post), but I thought it was just rounding. However, I refreshed the page and it showed "2 hours ago" immediately. 
It shows that time now, also after more refreshes. 

![Busy post time](http://www.steemimg.com/images/2017/01/21/233407CETcb30e.png)

This is impossible, since as I'm writing this, steemd.com [shows](https://steemd.com/stemms/@tibonova/pierce-the-butter-1485035761-9213154) "55 minutes ago" (and that's right).

**Comment by adcpm** [comment]
This issue seem to happen only on Firefox. Test here:
https://busy.org/created
https://steemit.com/created
