### ISSUE TITLE
Wrong Profile Image (different metadata)

### ISSUE THREAD

**Issue by mynameisek** [adcpm/busy#263]
on Steemit.com and Busy.org sometimes it picks wrong metadata and show different profile image

![image](https://cloud.githubusercontent.com/assets/8390894/22179817/7a9c09cc-e05e-11e6-8d76-914798841d04.png)
for example @the-ego-is-you
on busy.org
![image](https://cloud.githubusercontent.com/assets/8390894/22179840/db7258be-e05e-11e6-9cd9-42e06aaeebde.png)
two different pictures

**Comment by snowflake11** [comment]
This issue seem to only affect accounts starting with 'the' with a dash or a dot in username.
@the.masses
@the-ego-is-you
@the-future
@the-alien
@the-explorer
@the-reginald
@the.intercept

Note: I have seen the same issue on steemit.com with the.masses's account so the issue may not be related to busy's code but steemit.com's code.

**Comment by the-alien** [comment]
oh, I am so sad that it is so :sob:

**Comment by adcpm** [comment]
This issue has been solved by @nil1511
