### ISSUE TITLE
Tried to Log in with Steemit Creds.

### ISSUE THREAD

**Issue by RandyHilarski** [adcpm/busy#269]
Unexpected token < in JSON at position 0

http://www.200social.com/wp-content/uploads/2017/01/Busy.org_.png

**Comment by mynameisek** [comment]
which browser ?
do you use TOR ?

**Comment by RandyHilarski** [comment]
Hi Guys

I use Chrome for my browsing. No Tor.

Cheers,

*Randy Hilarski*
*High Impact Media Group Panama*
<http://www.highimpactmediagrouppanama.com/>
*LinkedIn* <http://pa.linkedin.com/in/randyhilarski>

**Comment by alexpmorris** [comment]
yeah, I've been having the same problem with steemconnect even with the demo account (@alexpmorris).  no TOR or proxy either.  Tried in chrome 32-bit, latest chrome 64-bit, and firefox - steemconnect acts the same way on all three.  However, firefox doesn't even bring up app.busy.org - returns a blank page, though it looks fine on chrome (though, not logged in of course).

**Comment by alexpmorris** [comment]
did you guys just change something?  I was trying to trace through the js code and suddenly it started saying "Invalid Password".  Next time I tried with the correct one, it worked -- I'm now logged into app.busy!

**Comment by adcpm** [comment]
Hey we had an issue we restarted the server and it's working again. We are still looking into it.

**Comment by nil1511** [comment]
@RandyHilarski Can you try again?
