### ISSUE TITLE
Some minor issues

### ISSUE THREAD

**Issue by snowflake11** [adcpm/busy#281]
Message cut out

![screen shot 2017-01-28 at 04 03 03](https://cloud.githubusercontent.com/assets/25279292/22394123/13d2a628-e50f-11e6-8673-580dd45d7537.png)

**Comment by p0o** [comment]
@snowflake11 Thank you for helping 👍  However, we need all these to be in separated issues since we need to connect each PR to the related issue and they might be solved in different phases. Please add new issues for all the other issues and edit this one to keep the first one here (if possible)

**Comment by snowflake11** [comment]
I just did. Sorry, didn't want to overload board with too many issues. Let me know if everything is ok.

**Comment by p0o** [comment]
@snowflake11 no worries it's a common practice here and again thanks for informing us about issues

**Comment by adcpm** [comment]
This issue has been fixed.
