### ISSUE TITLE
Downvote weight shows as positive 

### ISSUE THREAD

**Issue by snowflake11** [adcpm/busy#282]
![screen shot 2017-01-28 at 03 57 18](https://cloud.githubusercontent.com/assets/25279292/22394146/ae0d3320-e50f-11e6-868a-91225df05eed.png)

**Comment by snowflake11** [comment]
I found a similar bug

https://s23.postimg.org/xli0k0q2z/Screen_Shot_2017_02_05_at_16_34_17.png

**Comment by adcpm** [comment]
Do you have a link about these articles?

**Comment by snowflake11** [comment]
The first one no. 

But the second one is the post I wrote yesterday 
https://busy.org/steem/@snowflake/guardian-of-the-steem-universe-a-different-take-on-the-role-of-whales-within-steem-ecosystem
