### ISSUE TITLE
Notification number innacurate ( old notification also keeps coming back)

### ISSUE THREAD

**Issue by snowflake11** [adcpm/busy#285]
![screen shot 2017-01-28 at 04 20 55](https://cloud.githubusercontent.com/assets/25279292/22394208/87642560-e511-11e6-89a6-e5c3389b324d.png)

![screen shot 2017-01-28 at 04 21 45](https://cloud.githubusercontent.com/assets/25279292/22394211/91723ea2-e511-11e6-8da1-37b6cdd4d108.png)

**Comment by adcpm** [comment]
This issue has been solved
