### ISSUE TITLE
The account @null has broken profile picture

### ISSUE THREAD

**Issue by tibonova** [adcpm/busy#289]
It appears on the profile page like this

[![busy.null-avatar-profile9aed1.png](http://www.steemimg.com/images/2017/01/30/busy.null-avatar-profile9aed1.png)](http://www.steemimg.com/image/sBIo1)

It wouldn't be a big deal as no human follows that account, but it appears in the wallet history as well

[![busy.null-avatar3a50e.png](http://www.steemimg.com/images/2017/01/30/busy.null-avatar3a50e.png)](http://www.steemimg.com/image/sB9xU)

**Comment by nil1511** [comment]
Fixed in https://github.com/adcpm/steemconnect-img/commit/3714eb2e1f5ce926467bd1e5d8f7762705c57dbd
