### ISSUE TITLE
Texts on Donors page need an update

### ISSUE THREAD

**Issue by tibonova** [adcpm/busy#300]
It shows pre-release texts. 

---
[![busy.org.donors3bd34.png](http://www.steemimg.com/images/2017/02/02/busy.org.donors3bd34.png)](http://www.steemimg.com/image/sGTIe)

**Comment by adcpm** [comment]
The text has been updated on last changes.

**Comment by tibonova** [comment]
Sorry for asking, but I'm not a veteran here and I don't want to misunderstand you. 

What does your comment mean? It _will be_ updated on the live site or it should be already correct? Or the above image shows the correct date?
Because it was a fresh screenshot [from the page](https://busy.org/donors), which still shows Q1 2017, also after refreshes...

**Comment by adcpm** [comment]
Sorry the change has been made on the development repo, you can see it here dev.busy.org/donors. busy.org use the master repo where the changes happen later.
