### ISSUE TITLE
Scrolling Issue in Message Tab

### ISSUE THREAD

**Issue by clayop** [adcpm/busy#302]
I cannot scroll to the end of my list.

**Comment by adcpm** [comment]
@clayop Are you referring to the contact list on the sidebar?

**Comment by tibonova** [comment]
@adcpm It is a chat (channel) issue, for example [here](https://busy.org/messages/life).

**Comment by clayop** [comment]
@adcpm maybe rigjt. Sidetab on the left

**Comment by tibonova** [comment]
@clayop OK, I'll open a new issue for that then. 

Adding to this one, it's maybe a duplicate of #301

**Comment by adcpm** [comment]
Yes i'm closing this one it's a duplicate thx @tibonova @clayop
