### ISSUE TITLE
Receiving message notifications but not messages 

### ISSUE THREAD

**Issue by snowflake11** [adcpm/busy#306]
This is on chrome, so different than firefox issue

https://s30.postimg.org/i0w4812cx/Screen_Shot_2017_02_02_at_18_23_53.png

https://s28.postimg.org/amegmiwz1/Screen_Shot_2017_02_02_at_03_42_31.png

**Comment by snowflake11** [comment]
I think all those notifications are actually chat notifications. They should probably be seperate from message notifications somehow.

**Comment by adcpm** [comment]
I've been able to reproduce the issue. It happen when you talk to someone in private message like /messages/guest123 and this user write on a mutual channel like /messages/test. You would see a notification for the user while it's just an unread message in channel.
