### ISSUE TITLE
Youtube video shouldn't render when it's a Markdown link

### ISSUE THREAD

**Issue by tibonova** [adcpm/busy#309]
[![Screenshotfrom2017-02-0210-05-4755c58.md.png](http://www.steemimg.com/images/2017/02/02/Screenshotfrom2017-02-0210-05-4755c58.md.png)](http://www.steemimg.com/image/stR0L)
---

The image above shows a part of this post: [Busy](https://busy.org/steem/@tibonova/it-is-time-for-separating-downvotes-from-flags), [Steemit](https://steemit.com/steem/@tibonova/it-is-time-for-separating-downvotes-from-flags), [Steemd](https://steemd.com/steem/@tibonova/it-is-time-for-separating-downvotes-from-flags)

The relevant part of the post:
```
<center>[![joker meme](http://www.steemimg.com/images/2017/02/01/joker-madness-memebf03e.png)](https://youtu.be/Ylp5iKDFe10)
<sup>meme by @tibonova; click on the image for the scene uploaded by arcanus2344a</sup></center>
```

**Comment by pfunks** [comment]
Similarly other whitelisted embeds shouldn't auto-parse from links. See the end of this post:

Steemit, as intended: https://steemit.com/photography/@pfunk/spending-the-night-with-drumbeat-red-nomenclatures-and-extraterrestrials

Busy, auto-parsed: https://busy.org/photography/@pfunk/spending-the-night-with-drumbeat-red-nomenclatures-and-extraterrestrials

and a related question: Is there somewhere that whitelisted iframe services are listed?

**Comment by nil1511** [comment]
@pfunks Here is IframeWhiteList.
https://github.com/adcpm/busy/blob/dev/src/helpers/SanitizeConfig.js#L7
