### ISSUE TITLE
Additional parentheses in text, near to a Markdown link, cause issue

### ISSUE THREAD

**Issue by tibonova** [adcpm/busy#310]
[![Screenshotfrom2017-02-0210-05-278da4f.md.png](http://www.steemimg.com/images/2017/02/02/Screenshotfrom2017-02-0210-05-278da4f.png)](http://www.steemimg.com/image/st9Kl)

The image above shows a part of this post: [Busy](https://busy.org/steem/@tibonova/it-is-time-for-separating-downvotes-from-flags), [Steemit](https://steemit.com/steem/@tibonova/it-is-time-for-separating-downvotes-from-flags), [Steemd](https://steemd.com/steem/@tibonova/it-is-time-for-separating-downvotes-from-flags) 

The link shows the following URL on-hover: `https://busy.org/steem/@tibonova/<img src=`

The relevant part of the post:
```
If you have better connections than me (it's not hard, for I spend little time here for building relations and I am [forever alone](http://fakeplus.com/pictures/jpg/-forever-alone-level-99_20120609170014.jpg), lol), you could send this proposal closer to the decision makers.
```

Maybe connected with #309, in a sense that it wants to render an image when the image's URL is a part of a Markdown link. Or it's my first guess, the additional parentheses. I'm not sure.

**Comment by adcpm** [comment]
This is the related article: https://busy.org/steem/@tibonova/it-is-time-for-separating-downvotes-from-flags
