### ISSUE TITLE
Image embed from imgsafe.org missing on posts

### ISSUE THREAD

**Issue by mynameisek** [adcpm/busy#319]
![image](https://cloud.githubusercontent.com/assets/8390894/22616098/5f7852fc-eaa6-11e6-8d83-1530a50b8d52.png)
missing embed img from imgsafe.org (and maybe other possible issues)

https://busy.org/travel/@unlonely-soul/unique-park-of-forged-figures-part-3

**Comment by nil1511** [comment]
Closed in 0a68cc5
