### ISSUE TITLE
Chat body isn't scrollable

### ISSUE THREAD

**Issue by tibonova** [adcpm/busy#320]
I experienced it in a chat channel mode, for example [here](https://busy.org/messages/life). However, it could be also at personal messages what I haven't tested.

**Comment by adcpm** [comment]
The chat is scrollable for me. Do you have a screenshot about this? What browser are you using?

**Comment by tibonova** [comment]
I've just tested on Chromium too, where it is scrollable.

The issue is under Firefox.

**Comment by yamadapc** [comment]
Related to https://github.com/philipwalton/flexbugs/issues/42; will fix removing flexbox from the messages list layout.
