### ISSUE TITLE
Show png images with plain link 

### ISSUE THREAD

**Issue by clayop** [adcpm/busy#331]
e.g. https://busy.org/kr/@siloamlee/2uudwn

`http://i.imgsafe.org/73d5ac0d72.png` is shown just as a link.

Edit: Jpg images too. e.g. https://busy.org/photography/@abdullar/winter-sea-photos

**Comment by mynameisek** [comment]
closed in https://github.com/adcpm/busy/commit/0a68cc5b3005808aee918afb8e0d1e25d00957eb

https://github.com/adcpm/busy/issues/319
