### ISSUE TITLE
Image glitch via the image uploader

### ISSUE THREAD

**Issue by tibonova** [adcpm/busy#342]
So we have got a template. :smile:  

**About Issue** 
Using the image uploader cause image glitch which is saved upon publishing.

**Url(If any).**
The post was edited since.

**Expected behavior and actual behavior**
Instead of getting a Steem logo I've got what I posted below.

**Steps to reproduce the problem.**
Uploading the image I embedded here, wait a little, get the glitch, publish.

**Browser and version.**
FF. 51.0.1 (64-bit) Linux

**The real image**

---
![9bde1cd4d9a5b52ab4be8b0c8ed5a1e5.png](http://www.steemimg.com/images/2017/02/07/9bde1cd4d9a5b52ab4be8b0c8ed5a1e5.png)
---

**The screenshot of the glitched image**

---
![18259a83ab090bab0c807bcdfbe44cab.png](http://www.steemimg.com/images/2017/02/07/18259a83ab090bab0c807bcdfbe44cab.png)

**Comment by nil1511** [comment]
Fixed in https://github.com/adcpm/steemconnect-img/commit/375713aeea209a164117ccc713edfd40d04b787b
