### ISSUE TITLE
Chat deletes part of the message on submission

### ISSUE THREAD

**Issue by tibonova** [adcpm/busy#361]
#### Issue details

If I mention a user in the chat, it deletes all texts before the mentioned name on submission. Contents after the mention remain untouched. 
I've tried it in private message and chat channel mode, too. 

#### An example
`asdasd asdasd @tibonova qweqwe` will give `@tibonova qweqwe`

* Browser: Firefox 51.0.1
* OS: Ubuntu 16.10

**Comment by adcpm** [comment]
Thank you for reporting the issue, it's been fixed.
