### ISSUE TITLE
Code not embedded properly

### ISSUE THREAD

**Issue by snowflake11** [adcpm/busy#371]
![screen shot 2017-02-13 at 18 15 14](https://cloud.githubusercontent.com/assets/25279292/22907586/c07f495a-f241-11e6-924c-1cb23e503794.png)

**Comment by p0o** [comment]
@snowflake11 A link please? Are you sure it's not a mistake for the poster to post the `<iframe` code in his/her post? obviously HTML codes are not supported in markup.

**Comment by adcpm** [comment]
Here too https://dev.busy.org/bitshares/@guytremat/busy-paying-with-bitcoins-in-israel-by-bitgotechltd
