### ISSUE TITLE
Beginning of the comment is not displayed on busy.org

### ISSUE THREAD

**Issue by noisy** [adcpm/busy#374]
#### Expected behavior

Whole comment should be displayed :)

#### Actual behavior

Something is missing:

![selection_606](https://cloud.githubusercontent.com/assets/201263/22936822/f0371444-f2d6-11e6-8507-f6636026cc6c.png)

![selection_607](https://cloud.githubusercontent.com/assets/201263/22936829/f33954cc-f2d6-11e6-9eb7-f4ab7c8c9b8d.png)

#### How to reproduce

Go to: https://busy.org/steem/@tamim/price-of-steem

* Browser: Chrome, Version 54.0.2840.59 (64-bit)
* Operating system: Ubuntu 14.04 64

**Comment by adcpm** [comment]
Thank you for reporting the issue, it's been fixed.
