### ISSUE TITLE
Copyright/License?

### ISSUE THREAD

**Issue by pfunks** [adcpm/busy#377]
I searched for copyright and license but only found hits in .svg files. What copyright or license does the busy.org code fall under?

**Comment by mynameisek** [comment]
@pfunks working on it with our legal advisors, we're defining our 'final' model. For now it's busy.org 'project' which is under a french association umbrella, and the 'busy brand' is in process of being a registered trademark. (with certain condition that needs to be defined) The code is open source, opening the gpl/mit debate.. Our aim is to have something officially defined by the end of this month
thanks for opening the topic

**Comment by adcpm** [comment]
We chose MIT License.
