### ISSUE TITLE
Comment not working

### ISSUE THREAD

**Issue by snowflake11** [adcpm/busy#383]
https://busy.org/music/@surfermarly/can-you-feel-the-music

Tried to comment on this thread 
![screen shot 2017-02-19 at 18 38 49](https://cloud.githubusercontent.com/assets/25279292/23105251/0f09bc36-f6d4-11e6-8c3f-c5afa29dd918.png)

My avatar shows in comment section just after the comment was submitted but when i refresh and check the blockchain it's not there anymore.
Issue on both chrome and firefox.

**Comment by mynameisek** [comment]
same here!
![image](https://cloud.githubusercontent.com/assets/8390894/23106384/fe129812-f6ec-11e6-8fef-8efa985e8063.png)
@adcpm @nil1511 @p0o
