### ISSUE TITLE
Publish button loading is confusing

### ISSUE THREAD

**Issue by adcpm** [adcpm/busy#423]
#### Expected behavior

No loading on publish button

#### Actual behavior

When i upload a picture, the publish button will be changed in loading

#### How to reproduce

Go to busy.org/write and upload a picture. The publish button will be a loading for few seconds.

It's confusing, it feel like the post is being submited. See: 

![publish](https://cloud.githubusercontent.com/assets/16245250/24187709/c880a842-0f10-11e7-8f4d-232baf0a59ea.gif)

**Comment by nil1511** [comment]
how about image opacity for loading?

**Comment by adcpm** [comment]
I'm ok for image opacity, it would be better than the button loading.
