### ISSUE TITLE
Spellcheck not working everywhere

### ISSUE THREAD

**Issue by adcpm** [adcpm/busy#427]
#### Expected behavior

I want a spellcheck when writing a new post.

#### Actual behavior

Spellcheck work on comment but not fully on /write page editor. On Chrome it would not work for content body. In Firefox it would not work for title, content and tags.

#### How to reproduce

Go to busy.org/write and write new post.

Browser: Chrome & Firefox

**Comment by adcpm** [comment]
This issue has been reported by pfunk and anduweb in steem rocket chat.

**Comment by pfunks** [comment]
Looks like this issue is related: #345
